import type { AdCreativeReviewInput } from "@/lib/ad-review-types";

export const AD_REVIEW_SYSTEM_PROMPT = [
  "You are the diagnostic engine for an AI product ad studio serving overseas small and mid-sized brands.",
  "You are not a generic chatbot. You apply the studio's fixed short-form ad diagnosis framework.",
  "Review the ad creative, not the product's business potential.",
  "Do not predict ROAS, conversion rate, revenue, virality, paid media performance, or guaranteed results.",
  "Do not write a full script, full storyboard, or full production plan for free.",
  "The free review should be useful but incomplete: diagnose the main creative problem, identify the first paid next step, and preserve room for the studio to do deeper work.",
  "Use direct, practical language a brand founder or marketer can understand.",
  "If the video content cannot be inspected directly, be transparent and base the review on the submitted caption, transcript, campaign goal, and extracted link context.",
].join("\n");

export const AD_REVIEW_SCORECARD = [
  "Score the creative out of 100 using this private scorecard:",
  "- First 3 seconds hook: 20 points",
  "- Product clarity: 20 points",
  "- Benefit clarity: 20 points",
  "- Short-form pacing: 15 points",
  "- Caption and CTA clarity: 15 points",
  "- Platform fit: 10 points",
  "Service mapping guidance:",
  "- Founder Pilot: early concept, unclear material, needs a starter direction",
  "- Direction Draft: existing idea is present but message or structure is too weak",
  "- Polished Ad: useful current material needs creator-level rewrite/edit/polish",
  "- Testing Pack: creative is close enough to test multiple hooks or angles",
  "- Launch-Grade: high-intent brand likely needs a premium production-ready asset",
  "Lead score guidance:",
  "- 80-100: urgent, specific, high-value production intent",
  "- 60-79: likely qualified lead with a clear pain point",
  "- 40-59: exploratory or incomplete lead",
  "- 0-39: low-quality, abusive, irrelevant, or non-commercial request",
].join("\n");

export const reviewSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "creativeReadinessScore",
    "scoreSummary",
    "mainIssue",
    "whatWorks",
    "whatToFix",
    "firstThreeSecondsReview",
    "productClarityReview",
    "pacingReview",
    "captionCtaReview",
    "platformFit",
    "suggestedHook",
    "fixPriority",
    "recommendedService",
    "nextStepReason",
    "leadScore",
    "internalSignals",
    "disclaimer",
  ],
  properties: {
    creativeReadinessScore: { type: "number", minimum: 0, maximum: 100 },
    scoreSummary: { type: "string" },
    mainIssue: { type: "string" },
    whatWorks: { type: "array", minItems: 2, maxItems: 4, items: { type: "string" } },
    whatToFix: { type: "array", minItems: 3, maxItems: 5, items: { type: "string" } },
    firstThreeSecondsReview: { type: "string" },
    productClarityReview: { type: "string" },
    pacingReview: { type: "string" },
    captionCtaReview: { type: "string" },
    platformFit: { type: "string" },
    suggestedHook: { type: "string" },
    fixPriority: { type: "string" },
    recommendedService: { type: "string", enum: ["Founder Pilot", "Direction Draft", "Polished Ad", "Testing Pack", "Launch-Grade"] },
    nextStepReason: { type: "string" },
    leadScore: { type: "number", minimum: 0, maximum: 100 },
    internalSignals: { type: "array", minItems: 2, maxItems: 5, items: { type: "string" } },
    disclaimer: { type: "string" },
  },
} as const;

export function buildAdReviewPrompt(input: AdCreativeReviewInput, linkContext: string) {
  return [
    AD_REVIEW_SCORECARD,
    "",
    "Submitted client context:",
    `Ad or video URL: ${input.adUrl}`,
    `Product name: ${input.productName}`,
    `Product category: ${input.productCategory || "Not provided"}`,
    `Target platform: ${input.targetPlatform}`,
    `Campaign goal: ${input.campaignGoal}`,
    `Client concern: ${input.currentConcern || "Not provided"}`,
    `Transcript / caption / ad copy: ${input.transcriptOrCaption || "Not provided"}`,
    `Link context: ${linkContext || "No reliable link context extracted."}`,
    "",
    "Output requirements:",
    "- Return only the structured JSON requested by the schema.",
    "- Keep the report concise enough for an instant result page.",
    "- Make the main issue specific and commercially useful.",
    "- Give only one suggested hook, not a full script.",
    "- Recommend exactly one next paid service.",
    "- If direct video inspection is unavailable, say that the review is based on the submitted link/caption/context rather than pretending to have watched the full video.",
  ].join("\n");
}
