import type { AdCreativeReviewInput } from "@/lib/ad-review-types";

export const AD_REVIEW_SYSTEM_PROMPT = [
  "You are the diagnostic engine for VacaVaca Studio, an AI visual creative studio backed by the VACAT creator ecosystem.",
  "You review visual creative works, visual concepts, short films, key visuals, event visuals and campaign image systems.",
  "You are not a generic chatbot. You apply a fixed visual creative diagnosis framework.",
  "Review the submitted creative material, not the client's business potential.",
  "Do not predict ROAS, conversion rate, revenue, virality, paid media performance, or guaranteed results.",
  "Do not write a full script, full storyboard, or full production plan for free.",
  "The free review should be useful but incomplete: diagnose the main creative problem, identify the first paid next step, and preserve room for the studio to do deeper work.",
  "Use direct, practical language a founder, producer, curator, marketer or creative lead can understand.",
  "If the video or visual content cannot be inspected directly, be transparent and base the review on the submitted caption, transcript, project goal, and extracted link context.",
].join("\n");

export const AD_REVIEW_SCORECARD = [
  "Score the creative out of 100 using this private scorecard:",
  "- Opening moment: 20 points",
  "- Subject clarity: 20 points",
  "- Visual idea clarity: 20 points",
  "- Pacing and sequence: 15 points",
  "- Caption / ending clarity: 15 points",
  "- Format fit: 10 points",
  "Service mapping guidance:",
  "- Founder Pilot: early concept, unclear material, needs a starter direction",
  "- Direction Draft: existing idea is present but message or structure is too weak",
  "- Polished Visual: useful current material needs creator-level visual polish",
  "- Visual Sprint: creative is close enough to test multiple visual routes or angles",
  "- Launch-Grade: high-intent project likely needs a premium production-ready asset",
  "Lead score guidance:",
  "- 80-100: urgent, specific, high-value production intent",
  "- 60-79: likely qualified lead with a clear pain point",
  "- 40-59: exploratory or incomplete lead",
  "- 0-39: low-quality, abusive, irrelevant, or non-commercial request",
].join("\n");

export const reviewSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "creativeReadinessScore",
    "scoreSummary",
    "mainIssue",
    "whatWorks",
    "whatToFix",
    "firstThreeSecondsReview",
    "productClarityReview",
    "pacingReview",
    "captionCtaReview",
    "platformFit",
    "suggestedHook",
    "fixPriority",
    "recommendedService",
    "nextStepReason",
    "leadScore",
    "internalSignals",
    "disclaimer",
  ],
  properties: {
    creativeReadinessScore: { type: "number", minimum: 0, maximum: 100 },
    scoreSummary: { type: "string" },
    mainIssue: { type: "string" },
    whatWorks: { type: "array", minItems: 2, maxItems: 4, items: { type: "string" } },
    whatToFix: { type: "array", minItems: 3, maxItems: 5, items: { type: "string" } },
    firstThreeSecondsReview: { type: "string" },
    productClarityReview: { type: "string" },
    pacingReview: { type: "string" },
    captionCtaReview: { type: "string" },
    platformFit: { type: "string" },
    suggestedHook: { type: "string" },
    fixPriority: { type: "string" },
    recommendedService: { type: "string", enum: ["Founder Pilot", "Direction Draft", "Polished Visual", "Visual Sprint", "Launch-Grade"] },
    nextStepReason: { type: "string" },
    leadScore: { type: "number", minimum: 0, maximum: 100 },
    internalSignals: { type: "array", minItems: 2, maxItems: 5, items: { type: "string" } },
    disclaimer: { type: "string" },
  },
} as const;

export function buildAdReviewPrompt(input: AdCreativeReviewInput, linkContext: string) {
  return [
    AD_REVIEW_SCORECARD,
    "",
    "Submitted client context:",
    `Visual material URL: ${input.adUrl}`,
    `Project name: ${input.productName}`,
    `Project category: ${input.productCategory || "Not provided"}`,
    `Target format: ${input.targetPlatform}`,
    `Creative goal: ${input.campaignGoal}`,
    `Client concern: ${input.currentConcern || "Not provided"}`,
    `Transcript / caption / outline / copy: ${input.transcriptOrCaption || "Not provided"}`,
    `Link context: ${linkContext || "No reliable link context extracted."}`,
    "",
    "Output requirements:",
    "- Return only the structured JSON requested by the schema.",
    "- Keep the report concise enough for an instant result page.",
    "- Make the main issue specific and useful for visual creative production.",
    "- Give only one suggested opening, not a full script.",
    "- Recommend exactly one next paid service.",
    "- If direct video inspection is unavailable, say that the review is based on the submitted link/caption/context rather than pretending to have watched the full video.",
  ].join("\n");
}
